### ISSUE TITLE
关于蓝牙配网部分无法传递ssid和pwd的值的问题。

### ISSUE THREAD

**Issue by xpdrycry** [EspressifApp/EspMeshForAndroid#5]
最近看了一下，你们提供的espmesh小程序，那里可以实现进行，可以吧ssid和pwd传递过去，不知道android的为什么不行。也没有查出问题来。

**Comment by XuXiangJun** [comment]
同一台手机小程序可以用，Android 客户端不行？

**Comment by xpdrycry** [comment]
是的，用的是同一台手机。小程序(EspMesh)可以用，但是android客户端不可以用.
